# This is a basic workflow to help you get started with Actions
# Documentation about plugins in use could be found there https://github.com/rtCamp/action-slack-notify

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ maintenance/* ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@master
      env:
        SLACK_CHANNEL: "@Pierre-Alban Dewitte"
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_USERNAME: "TMC Release bot"
        SLACK_ICON_EMOJI: ":information_source:"
        SLACK_FOOTER: "new addition to maintenance branch ${GITHUB_REF##*/}"
        
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: Branch name
      run: echo running on branch ${GITHUB_REF##*/}
    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Commit added to maintenance branch ${GITHUB_REF##*/}!
